version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    working_directory: ~/editor
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-deps
          command: npm install
      - run:
          name: build-packages
          command: npm run lint
      - run:
          name: build
          command: npm run build
      - persist_to_workspace:
          root: ~/editor
          paths:
              - "*"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
